NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/r18_cub200_224_e100_sgd_mslr'
TRAIN:
  LOG_STEP: 10
  GRADIENT_ACCUMULATE_STEP: 1
  MAX_EPOCH: 100
  SAVE_EPOCH: 5
  EVAL_EPOCH: 5
  RESUME: False
  USE_TENSORBOARD: True
  HYBRID_PRECISION: True
DATASET:
  NAME: 'MPDataset'
  TRAIN_ROOT: './data/cub/train'
  TEST_ROOT: './data/cub/test'
  TOP_K: (1, 5)
TRANSFORM:
  TRAIN_METHODS: ('Resize', 'RandomCrop', 'HorizontalFlip', 'AutoAugment', 'Normalize', 'ToTensor')
  TEST_METHODS: ('Resize', 'CenterCrop', 'Normalize', 'ToTensor')
  TRAIN_RESIZE: ((256, ), 1, 0, 1.0)
  RANDOM_CROP: ((224, 224), 1.0)
  TEST_RESIZE: ((224, ), 1, 0, 1.0)
  TEST_CENTER_CROP: ((224, 224), 1.0)
  HORIZONTAL_FLIP: 0.5
  AUTOAUGMENT: ("cifar10", 1.0)
  NORMALIZE: ((0.485, 0.456, 0.406), (0.229, 0.224, 0.225), 255.0, 1.0)
  TO_TENSOR: 1.0
DATALOADER:
  TRAIN_BATCH_SIZE: 128
  TEST_BATCH_SIZE: 128
  NUM_WORKERS: 4
  RANDOM_SAMPLE: True
  PREFETCHER: True
MODEL:
  BACKBONE:
    ARCH: 'resnet18'
  HEAD:
    NUM_CLASSES: 200
  RECOGNIZER:
    NAME: 'TorchvisionResNet'
    PRETRAINED_REMOTE: True
    PRELOADED: 'outputs/r18_cub200_224_e100_sgd_mslr/model_0085.pth'
  CRITERION:
    NAME: 'CrossEntropyLoss'
OPTIMIZER:
  NAME: 'SGD'
  LR: 0.05
  MOMENTUM: 0.9
  WEIGHT_DECAY:
    DECAY: 1e-4
    NO_BIAS: True
    NO_NORM: True
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  GAMMA: 0.1
  MULTISTEP_LR:
    MILESTONES: [ 30, 60, 90 ]
  WARMUP:
    ITERATION: 5
    MULTIPLIER: 1.0